"""
compute_h4_per_model.py
-----------------------------------------------------------------------
Closes the significance-testing gap in dissertation Figure 5.5b.

WHAT THIS DOES
--------------
Figure 5.5 (the pooled H4 result) comes from test_h4() in
phase_b_statistical_analysis.py, which fits ONE mixed-effects model
across all three models' tile data together:

    cosine_similarity ~ C(perturbation_id), groups = "model"

This gives a single set of perturbation coefficients (and p-values)
pooled across models, with "which model" absorbed as a random intercept.
It cannot tell you whether UNI specifically is more or less sensitive to
a given perturbation than CONCH or Prov-GigaPath -- only the pooled,
averaged effect.

Figure 5.5b instead computed each model's own coefficients directly from
already-averaged summary numbers (the same numbers behind Table 5.2), so
it has no p-values and no significance stars: you cannot run a
significance test on numbers that are already averages, only on the
individual tile-level measurements behind them.

This script closes that gap properly, by fitting the SAME KIND OF
MODEL as test_h4(), just once per model instead of once pooled. Because
each fit only sees one model's data, the "groups" / random-intercept
part of the original formula becomes unnecessary (there's nothing left
to pool over), so this collapses to an ordinary least-squares regression:

    cosine_similarity ~ C(perturbation_id)

...fit separately on each model's own subset of the raw tile-level data.
This is simpler and faster to fit than the original pooled mixed model,
not more complex -- no "did it converge" risk, no singular-matrix risk.

INPUT
-----
The raw cosine_similarity.csv produced by
extract_embeddings_similarity.py --mode similarity (the same file
phase_b_statistical_analysis.py's H4 pooled test already consumes).
Required columns (checked at load time, matching
phase_b_statistical_analysis.py's own REQUIRED_COSINE_COLUMNS):
    model, sample_id, cohort, perturbation_id, severity, cosine_similarity

OUTPUT
------
option_{a,b}_h4_per_model.csv, one row per (model, perturbation_id):
    model, perturbation_id, n_tiles, coef, p_value,
    p_value_bonferroni, significant_bonferroni

coef is the change in cosine similarity for that perturbation relative
to Perturbation 01 (the reference level), for that model alone -- the
per-model analogue of the numbers already plotted in Figure 5.5b, now
with a real p-value attached to each one.

Bonferroni correction defaults to alpha = 0.05/54, matching the
threshold already used everywhere else in the dissertation (3 pairwise
comparisons x 18 perturbations = 54), for consistency with the rest of
the document. The script also prints the exact number of tests actually
run here (17 non-reference perturbations x 3 models = 51) so a stricter,
more technically precise alpha = 0.05/51 can be substituted instead if
preferred -- see --alpha-denominator below.

USAGE
-----
    python3 compute_h4_per_model.py \\
        --cosine-csv /path/to/cosine_similarity.csv \\
        --option b \\
        --out-dir /path/to/output

Run --help for all options.
-----------------------------------------------------------------------
"""
import argparse
from pathlib import Path

import numpy as np
import pandas as pd
import statsmodels.formula.api as smf

REQUIRED_COLUMNS = {"model", "sample_id", "cohort", "perturbation_id", "severity", "cosine_similarity"}

MODEL_SETS = {
    "a": ["uni", "conch", "quilt_llava"],
    "b": ["uni", "conch", "gigapath_tile"],
}


def load_cosine_data(path: Path) -> pd.DataFrame:
    """Loads and validates cosine_similarity.csv, matching the same check
    phase_b_statistical_analysis.py's load_cosine_data() performs, so a
    schema mismatch fails fast and clearly rather than downstream."""
    print(f"Loading cosine similarity data from {path} ...")
    df = pd.read_csv(path)
    missing = REQUIRED_COLUMNS - set(df.columns)
    if missing:
        raise ValueError(
            f"cosine_similarity.csv at {path} is missing required column(s) "
            f"{sorted(missing)}. Was this generated by an older version of "
            f"extract_embeddings_similarity.py's run_similarity()? "
            f"Re-run --mode similarity."
        )
    print(f"Loaded {len(df):,} rows across models: {sorted(df['model'].unique())}")
    return df


def fit_one_model(df: pd.DataFrame, model_name: str) -> pd.DataFrame:
    """
    Fits cosine_similarity ~ C(perturbation_id) on a single model's own
    tile-level rows only -- the per-model analogue of test_h4()'s pooled
    mixed model, minus the now-unnecessary "groups" / random-intercept
    term, since there is only one model in this subset.
    """
    subset = df[df["model"] == model_name].copy()
    subset = subset.dropna(subset=["cosine_similarity"])
    subset["perturbation_id"] = subset["perturbation_id"].astype("category")

    n_tiles = len(subset)
    print(f"  Fitting OLS for {model_name} on {n_tiles:,} tile-level rows ...")

    ols_model = smf.ols("cosine_similarity ~ C(perturbation_id)", data=subset)
    fit = ols_model.fit()

    rows = []
    for term, coef in fit.params.items():
        if term == "Intercept":
            continue
        # statsmodels formats dummy terms like "C(perturbation_id)[T.9]"
        pid = int(term.split("[T.")[1].rstrip("]"))
        rows.append({
            "model": model_name,
            "perturbation_id": pid,
            "n_tiles": n_tiles,
            "coef": float(coef),
            "p_value": float(fit.pvalues[term]),
        })
    return pd.DataFrame(rows)


def main():
    parser = argparse.ArgumentParser(
        description="Fit per-model H4 perturbation significance tests, closing the "
                    "gap left by Figure 5.5b's descriptive-only per-model breakdown."
    )
    parser.add_argument("--cosine-csv", required=True, type=Path,
                        help="Path to the raw cosine_similarity.csv (one row per tile).")
    parser.add_argument("--option", required=True, choices=["a", "b"],
                        help="Which model cohort configuration to fit (a or b).")
    parser.add_argument("--out-dir", required=True, type=Path,
                        help="Directory to write option_{a,b}_h4_per_model.csv to.")
    parser.add_argument("--alpha-denominator", type=int, default=54,
                        help="Bonferroni denominator (default 54, matching the rest of "
                             "the dissertation; the exact number of tests run here is "
                             "printed at the end -- pass that value instead for a "
                             "stricter, exact correction if preferred).")
    args = parser.parse_args()

    args.out_dir.mkdir(parents=True, exist_ok=True)
    df = load_cosine_data(args.cosine_csv)

    models = MODEL_SETS[args.option]
    present = set(df["model"].unique())
    missing_models = [m for m in models if m not in present]
    if missing_models:
        raise ValueError(
            f"Expected models {models} for option {args.option}, "
            f"but {missing_models} not found in the data. "
            f"Models present: {sorted(present)}"
        )

    all_rows = []
    for m in models:
        all_rows.append(fit_one_model(df, m))
    result = pd.concat(all_rows, ignore_index=True)

    alpha = 0.05 / args.alpha_denominator
    result["p_value_bonferroni"] = (result["p_value"] * args.alpha_denominator).clip(upper=1.0)
    result["significant_bonferroni"] = result["p_value"] < alpha

    out_path = args.out_dir / f"option_{args.option}_h4_per_model.csv"
    result.to_csv(out_path, index=False)

    n_tests_run = len(result)
    print(f"\nWrote {out_path} ({n_tests_run} rows: {len(models)} models x "
          f"{n_tests_run // len(models)} non-reference perturbations)")
    print(f"Bonferroni correction used: alpha = 0.05/{args.alpha_denominator} = {alpha:.6f}")
    print(f"Exact number of tests actually run here: {n_tests_run} "
          f"(for a stricter exact correction, re-run with "
          f"--alpha-denominator {n_tests_run})")
    print(f"Significant at this threshold: {result['significant_bonferroni'].sum()} / {n_tests_run}")


if __name__ == "__main__":
    main()
